baseURL = "http://example.org/"
languageCode = "zh-tw"
title = "ğŸ¤é´¨è„†ç„¡è²çš„ç”Ÿæ´»ç­†è¨˜âœ¨"
theme = "PaperMod"
enableEmoji = true

[params]
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"

[menu]

  [[menu.main]]
    name = "ğŸ  é¦–é "
    url = "/"
    weight = 1

  [[menu.main]]
    name = "ğŸ“ ç­†è¨˜"
    url = "/posts"
    weight = 2

  [[menu.main]]
    name = "ğŸ“– é—œæ–¼æˆ‘"
    url = "/about"
    weight = 3
